[package]
name = "tdx-attestation"
version = "0.1.0"
edition = "2021"

[dependencies]
dstack-core = {workspace=true}
async-trait = {workspace=true}
anyhow = {workspace=true}
hex = {workspace=true}
sha2 = {workspace=true}
tdx-attest = {path="../attestation-driver/tdx-attest"}
dcap-qvl = "0.1.6"
