name = "newyork"

[[tables]]
name = "pending"

[[tables.columns]]
name = "pubkey"
col_type = "BYTEA"

[[tables.columns]]
name = "quote"
col_type = "BYTEA"

[[tables.columns]]
name = "at_time"
col_type = "BYTEA"


[[tables]]
name = "onboard"

[[tables.columns]]
name = "pubkey"
col_type = "BYTEA"

[[tables.columns]]
name = "encrypted"
col_type = "BYTEA"

[[tables.columns]]
name = "at_time"
col_type = "BYTEA"

