[package]
name = "dummy-attestation"
version = "0.1.0"
edition = "2021"

[dependencies]
dstack-core = {workspace=true}
async-trait = {workspace=true}
anyhow = {workspace=true}
dcap-quotes = {workspace=true}
hex = {workspace=true}
sha2 = {workspace=true}
reqwest = {workspace=true}